QLSachOnline/QLSachOnline/Models/tacgia.cs
namespace QLSachOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("tacgia")]
    public partial class tacgia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tacgia()
        {
            saches = new HashSet<sach>();
        }

        [Key]
        [StringLength(20),Display(Name ="Mã tác giả")]
        [Required(ErrorMessage ="Vui lòng nhập mã tác giả !")]
        public string matg { get; set; }

        [StringLength(50), Display(Name = "Tên tác giả")]
        [Required(ErrorMessage = "Vui lòng nhập tên tác giả !")]
        public string tentg { get; set; }

        [Display(Name = "Ngày sinh")]
        public DateTime? ngaysinh { get; set; }

        [StringLength(50), Display(Name = "Quê quán")]
        public string quequan { get; set; }

        [StringLength(20), Display(Name = "Nghệ danh")]
        public string nghedanh { get; set; }
        [Display(Name = "Giới tính")]
        public bool? gioitinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sach> saches { get; set; }

        public string getGioiTinh() { return (bool)gioitinh ? "Nam" : "Nữ"; }
        public string toString()
        {
            return "Mã: " + matg + "</br>Ngày sinh: " + ngaysinh.Value.ToShortDateString() + "</br>Giới tính:" + getGioiTinh() + "</br>Quê quán:" + quequan;
        }
    }
}

QLSachOnline/QLSachOnline/Controllers/TacGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLSachOnline.Controllers
{
    public class TacGiaController : Controller
    {
        private Models.QLySachOnline db = new Models.QLySachOnline();
        // GET: TacGia
        public ActionResult QuanLyTacGia()
        {
            return View(db.tacgias);
        }
        public ActionResult formThemTacGia()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult themTacGia(Models.tacgia tg)
        {
            if (ModelState.IsValid)
            {
                if (db.tacgias.Find(tg.matg) == null)
                {
                    tg.matg = tg.matg.ToUpper();
                    db.tacgias.Add(tg);
                    db.SaveChanges();
                    return RedirectToAction("QuanLyTacGia");
                }
                ModelState.AddModelError("matg", "Mã trùng vui lòng nhập lại !");
            }
            return View("formThemTacGia");
        }
        public ActionResult formXoaTacGia(string id)
        {
            if (db.tacgias.Find(id).saches.Count == 0)
                ViewBag.flagXoa = true;
            return View(db.tacgias.Find(id));
        }
        
        [HttpPost]
        public ActionResult xoaTacGia()
        { 
            Models.tacgia tg = db.tacgias.Find(Request["matg"].ToString());
            db.tacgias.Remove(tg);
            db.SaveChanges();
            return RedirectToAction("QuanLyTacGia");
        }
        public ActionResult formChiTietTacGia(string id)
        {
            return View(db.tacgias.Find(id));
        }
        public ActionResult formChinhSuaTG(string id)
        {
            return View(db.tacgias.Find(id));
        }
        
        [HttpPost]
        public ActionResult chinhSuaTG(Models.tacgia x)
        {
            if (ModelState.IsValid)
            {
                Models.tacgia tg = db.tacgias.Find(x.matg);
                tg.tentg = x.tentg;
                tg.ngaysinh = x.ngaysinh;
                tg.gioitinh = x.gioitinh;
                tg.quequan = x.quequan;
                tg.nghedanh = x.nghedanh;
            }
            
            db.SaveChanges();
            return RedirectToAction("QuanLyTacGia");
        }
    }
}

QLSachOnline/QLSachOnline/Views/TacGia/QuanLyTacGia.cshtml
@model IEnumerable<QLSachOnline.Models.tacgia>
@{
    ViewBag.Title = "Quản lý tác giả";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Quản lý tác giả</h2>
                    <a href="@Url.Content("/TacGia/formThemTacGia")" class="btn btn-primary">Thêm tác giả</a>
                </div>

                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Mã tác giả</th>
                                <th>Tên tác giả</th>
                                <th>Ngày sinh</th>
                                <th>Giới tính</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(ModelItem => item.matg)</td>
                                    <td><a href="@Url.Content("/TacGia/formChiTietTacGia/"+item.matg)">@Html.DisplayFor(ModelItem => item.tentg)</a></td>
                                    <td>@item.ngaysinh.Value.ToShortDateString()</td>
                                    <td>@(item.gioitinh.Equals(true) ? "Nam" : "Nữ")</td>
                                    <td><a href="@Url.Content("/TacGia/formXoaTacGia/"+item.matg)" class="btn btn-outline-primary">Xóa</a></td>
                                    <td><a href="@Url.Content("/TacGia/formChinhSuaTG/"+item.matg)" class="btn btn-outline-primary">Chỉnh sửa</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

QLSachOnline/QLSachOnline/Views/TacGia/formChiTietTacGia.cshtml
@model QLSachOnline.Models.tacgia
@{
    ViewBag.Title = "Chi tiết tác giả";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}


<div class="container-fluid">
    <div class="card">
        <div class="card-header"><h2>Chi tiết tác giả</h2></div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-2 font-weight-bold">Mã tác giả:</div>
                <div class="col-md-10">@Model.matg</div>
            </div>
            <div class="row">
                <div class="col-md-2 font-weight-bold">Tên tác giả:</div>
                <div class="col-md-10">@Model.tentg</div>
            </div>
            <div class="row">
                <div class="col-md-2 font-weight-bold">Ngày sinh:</div>
                <div class="col-md-10">@Model.ngaysinh.Value.ToShortDateString()</div>
            </div>
            <div class="row">
                <div class="col-md-12 font-weight-bold">Giới tính: @((bool)Model.gioitinh?"Nam":"Nữ")</div>
            </div>
            <div class="row">
                <div class="col-md-2 font-weight-bold">Quê quán:</div>
                <div class="col-md-10">@Model.quequan</div>
            </div>
            <div class="row">
                <div class="col-md-2 font-weight-bold">Nghệ danh:</div>
                <div class="col-md-10">@Model.nghedanh</div>
            </div>
            <div class="row">
                <div class="col-md-3 font-weight-bold">Số lượng tác phẩm có trên trang:</div>
                <div class="col-md-9">@Model.saches.Count</div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-3 col-6"><a href="@Url.Content("/TacGia/formChinhSuaTG/"+Model.matg)" class="btn btn-primary">Chỉnh sửa</a></div>
                <div class="col-md-9 col-6"><a href="@Url.Content("/TacGia/formThemTacGia")" class="btn btn-primary">Thêm tác giả</a></div>
            </div>
        </div>
    </div>
</div>

QLSachOnline/QLSachOnline/Views/TacGia/formChinhSuaTG.cshtml
@model QLSachOnline.Models.tacgia

@{
    ViewBag.Title = "Chỉnh sửa tác giả";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="col-md-10">
    <h2>Thêm tác giả</h2>
    @using (Html.BeginForm("chinhSuaTG", "TacGia", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.matg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.matg, new { htmlAttributes = new { @class = "form-control" ,@readonly="readonly"} })
                    @Html.ValidationMessageFor(model => model.matg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tentg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tentg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tentg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ngaysinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ngaysinh, "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control", @type = "date"})
                    @Html.ValidationMessageFor(model => model.ngaysinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gioitinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.gioitinh, new List<SelectListItem> { new SelectListItem { Text = "Nam", Value = "true" }, new SelectListItem { Text = "Nữ", Value = "false" } }, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.gioitinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.quequan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.quequan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quequan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nghedanh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nghedanh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nghedanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

QLSachOnline/QLSachOnline/Views/TacGia/formThemTacGia.cshtml
@model QLSachOnline.Models.tacgia

@{
    ViewBag.Title = "Thêm tác giả";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}
<div class="col-md-10">
    <h2>Thêm tác giả</h2>
    @using (Html.BeginForm("themTacGia", "TacGia", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.matg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.matg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.matg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tentg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tentg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tentg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ngaysinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngaysinh, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.ngaysinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gioitinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.gioitinh, new List<SelectListItem> { new SelectListItem { Text = "Nam", Value = "true" }, new SelectListItem { Text = "Nữ", Value = "false" } }, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.gioitinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.quequan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.quequan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quequan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nghedanh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nghedanh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nghedanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

QLSachOnline/QLSachOnline/Views/TacGia/formXoaTacGia.cshtml
@model QLSachOnline.Models.tacgia
@{
    ViewBag.Title = "Xóa tác giả";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}



<div class="container-fluid">
    <div class="card">
        <div class="card-header"><h2>Xóa tác giả</h2></div>
        <div class="card-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.matg)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.matg)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.tentg)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tentg)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ngaysinh)
                </dt>

                <dd>
                    @Model.ngaysinh.Value.ToShortDateString()
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.quequan)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.quequan)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.nghedanh)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nghedanh)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.gioitinh)
                </dt>

                <dd>
                    @((bool)Model.gioitinh?"Nam":"Nữ")
                </dd>

            </dl>
        </div>
        <div class="card-footer">
            @if (ViewBag.flagXoa != null)
            {
                using (Html.BeginForm("xoaTacGia", "TacGia", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.matg)
                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa" class="btn btn-outline-danger" />
                    </div>
                }
            }
            else
            {
                <h3 class="alert alert-danger"><strong>Cảnh báo !!</strong>Không thể xóa</h3>
            }
        </div>
    </div>
</div>