QLSachOnline/QLSachOnline/Models/goi.cs
namespace QLSachOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("goi")]
    public partial class goi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public goi()
        {
            usergois = new HashSet<usergoi>();
        }

        [Key]
        [StringLength(10), Display(Name = "Mã gói")]
        [Required(ErrorMessage = "Vui lòng nhập mã gói !")]
        public string magoi { get; set; }

        [StringLength(100), Display(Name = "Tên gói")]
        [Required(ErrorMessage = "Vui lòng nhập tên gói !")]
        public string tengoi { get; set; }

        [Display(Name = "Mô tả gói")]
        public string motagoi { get; set; }

        [Display(Name = "Thời hạn gói")]
        [Required(ErrorMessage = "Vui lòng nhập thời hạn gói !")]
        public int thoihan { get; set; }

        [Column(TypeName = "money"),Display(Name ="Giá")]
        public decimal? gia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usergoi> usergois { get; set; }
    }
}

QLSachOnline/QLSachOnline/Controllers/GoiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLSachOnline.Controllers
{
    public class GoiController : Controller
    {
        QLSachOnline.Models.QLySachOnline db = new Models.QLySachOnline();
        // phần hiển thị bên user
        public ActionResult IndexGoi(string id)
        {
            // id ở đây là mã sách từ indexSach truyền qua
            if (id != null)
            {
                Session.Add("flagMaSach", id);
            }
            return View(db.gois.ToList());
        }

        public ActionResult chiTietGoi(string id)
        {
            if (TempData["flagBackGoi"] != null)
                id = TempData["flagBackGoi"] as string;
            return View(db.gois.Find(id));
        }

        // Phần thanh toán
        public ActionResult thanhToanGoi(string id)
        {
            if ((bool)Session["isLogin"])
            {
                Models.goi goi = db.gois.Find(id);
                Models.userlogin userlogin = Session["Login"] as Models.userlogin;
                Models.usergoi usergoi = new Models.usergoi();
                usergoi.magoi = id;
                usergoi.taikhoan = userlogin.taikhoan;
                usergoi.ngaymua = System.DateTime.Now;
                if (userlogin.usergois.Where(a => a.ngayhethan >= System.DateTime.Now).ToList().Count == 0)
                    usergoi.ngayhethan = System.DateTime.Now.AddDays(goi.thoihan);
                else
                    usergoi.ngayhethan = userlogin.usergois.ToList().Last().ngayhethan.AddDays(goi.thoihan);//lấy giá trị ngày hết hạn của thằng cuối cộng thêm
                
                double tongNgay = (usergoi.ngayhethan - System.DateTime.Now).TotalDays;

                db.usergois.Add(usergoi);
                db.SaveChanges();

                Session["Login"] = db.userlogins.Find(userlogin.taikhoan);
                userlogin = Session["Login"] as Models.userlogin;
                Session["isHavingPremium"] = true;

                Session["PDays"] = (int)Math.Floor(tongNgay);
                Session["PHours"] = DateTime.FromOADate(tongNgay - Math.Floor(tongNgay)).Hour;
                Session["PMinutes"] = DateTime.FromOADate(tongNgay - Math.Floor(tongNgay)).Minute;

                if (Session["flagMaSach"] != null)
                    return RedirectToAction("indexSach", "Sach");
                return RedirectToAction("Index","Home");
            }
            TempData["flagBackGoi"] = id;
            return RedirectToAction("IndexDangNhap","User");
        }

        //Phần bên admin
        public ActionResult QuanLyGoi()
        {
            return View(db.gois.ToList());
        }

        public ActionResult formThemGoi()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult themGoi(Models.goi goi)
        {
            if (ModelState.IsValid)
            {
                if (db.gois.Find(goi.magoi) == null)
                {
                    goi.magoi = goi.magoi.ToUpper();
                    db.gois.Add(goi);
                    db.SaveChanges();
                    return RedirectToAction("QuanLyGoi");
                }
                ModelState.AddModelError("magoi", "Mã trùng ! Vui lòng nhập mã khác !");
            }
            return View("formThemGoi");
        }

        public ActionResult formSuaGoi(string id)
        {
            return View(db.gois.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult suaGoi(Models.goi goi)
        {
            if (ModelState.IsValid)
            {
                Models.goi goiSua = db.gois.Find(goi.magoi);
                if ( goiSua != null)
                {
                    goiSua.tengoi = goi.tengoi;
                    goiSua.motagoi = goi.motagoi;
                    goiSua.thoihan = goi.thoihan;
                    //giá
                    db.SaveChanges();
                }    
            }
            return RedirectToAction("QuanLyGoi");
        }
        public ActionResult formXoaGoi(string id)
        {
            Models.goi goi = db.gois.Find(id);
            if (goi.usergois.Count == 0)
                ViewBag.flagCheck = true;
            return View(db.gois.Find(id));
        }


    }
}

QLSachOnline/QLSachOnline/Views/Goi/IndexGoi.cshtml
@model IEnumerable<QLSachOnline.Models.goi>

@{
    ViewBag.Title = "Gói Premium";
    Layout = "~/Views/_Layout/_LayoutDangNhapDangKy.cshtml";
}

<!-- ======= Gói Section ======= -->
<section id="featured-services" class="featured-services bg-white rounded-2">
    <div class="container" data-aos="fade-up">

        <div class="row align-items-center">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-3 col-12 mb-5 mb-lg-0">
                    <a href="@Url.Content("/Goi/chiTietGoi/"+item.magoi)" class="text-black text-center">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                            <div class="icon text-danger"><i class="fas fa-gem fa-5x"></i></div>
                            <h4 class="title">@item.tengoi</h4>
                            <p class="description">@item.motagoi</p>
                            <div><strong>Giá:&nbsp;</strong>@String.Format("{0:n0}", item.gia) <strong>&nbsp;VNĐ</strong></div>
                        </div>
                    </a>
                </div>
            }
        </div>

    </div>
</section><!-- End Gói Section -->

QLSachOnline/QLSachOnline/Views/Goi/QuanLyGoi.cshtml
@model IEnumerable<QLSachOnline.Models.goi>

@{
    ViewBag.Title = "Quản lý gói";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Quản lý gói</h2>
                    <a href="@Url.Content("/Goi/formThemGoi")" class="btn btn-primary">Thêm gói Premium</a>
                </div>

                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Mã gói</th>
                                <th>Tên gói</th>
                                <th>Thời hạn</th>
                                <th>Giá</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.magoi</td>
                                    <td><a href="#" class="text-decoration-none">@item.tengoi</a></td>
                                    <td>@item.thoihan<strong>&nbsp;Ngày</strong></td>
                                    <td>@String.Format("{0:n0}", item.gia) <strong>&nbsp;VNĐ</strong></td>
                                    <td><a href="@Url.Content("/Goi/formXoaGoi/"+item.magoi)" class="btn btn-outline-primary">Xóa</a></td>
                                    <td><a href="@Url.Content("/Goi/formSuaGoi/"+item.magoi)" class="btn btn-outline-primary">Chỉnh sửa</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

QLSachOnline/QLSachOnline/Views/Goi/chiTietGoi.cshtml
@model QLSachOnline.Models.goi

@{
    ViewBag.Title = "Chọn gói";
    Layout = "~/Views/_Layout/_LayoutDangNhapDangKy.cshtml";
}

<!-- ======= Chi tiết gói/ thanh toán Section ======= -->
<section id="portfolio-details" class="portfolio-details bg-white" style="border-radius:30px;">
    <div class="container">

        <div class="row gy-4 d-flex justify-content-center">

            <div class="col-lg-6">
                <div class="portfolio-info row" style="background-color: white;">
                    <div class="col-md-12 col-lg-12 col-12 mb-5 mb-lg-0">
                        <div class="section-title">
                            <h2>Gói Premium &nbsp;<i class="fas fa-gem text-danger"></i></h2>
                            <h3>Premium <span>@Model.tengoi</span></h3>
                        </div>
                        <div class="row">
                            <div class="col-7">
                                <ul>
                                    <li><strong>Tên gói</strong>: @Model.tengoi</li>
                                    <li><strong>Thời hạn</strong>: @Model.thoihan &nbsp; <strong>Ngày</strong></li>
                                    <li><strong>Giá</strong>: @String.Format("{0:n0}", Model.gia) &nbsp; <strong>VNĐ</strong></li>
                                </ul>
                            </div>
                            <div class="col-5">
                                <strong>Mô tả gói:</strong>
                                @Model.motagoi
                            </div>
                        </div>
                        <hr>
                        <div class="text-center"><a href="@Url.Content("/Home/chonPhuongThucThanhToan/"+Model.magoi)" class="btn btn-success"><i class="fas fa-money-bill-alt"></i>&nbsp;Thanh toán</a></div>

                    </div>
                </div>
            </div>


            <div class="col-lg-1">&nbsp;</div>


            <div class="col-lg-3 col-12">
                <div class="portfolio-info row" style="background-color: white;">
                    <div class="col-md-12 col-lg-12 col-12 mb-5 mb-lg-0">

                        <section id="featured-services" class="featured-services">
                            <div class="container" data-aos="fade-up">

                                <div class="section-title">
                                    <h2>Các gói được mua nhiều nhất trong tháng &nbsp;<i class="fas fa-gem text-danger"></i></h2>
                                </div>
                                @{
                                    QLSachOnline.Models.QLySachOnline db = new QLSachOnline.Models.QLySachOnline();
                                    List<QLSachOnline.Models.goi> dsGoi = new List<QLSachOnline.Models.goi>();

                                    for (int i = 0; i < db.gois.Count(); i++)
                                    {
                                        string ma = db.gois.ToArray()[i].magoi;
                                        int max = db.usergois.Where(x => x.magoi == ma).ToList().Count;
                                        foreach (var item in db.gois)
                                        {
                                            if (db.usergois.Where(x => x.magoi == item.magoi).ToList().Count > max)
                                            {
                                                if (!dsGoi.Contains(db.gois.Find(item.magoi)))
                                                {
                                                    max = db.usergois.Where(x => x.magoi == item.magoi).ToList().Count;
                                                    ma = item.magoi;
                                                }
                                            }
                                        }
                                        if (!dsGoi.Contains(db.gois.Find(ma))) {
                                            dsGoi.Add(db.gois.Find(ma));
                                        }
                                    }
                                    foreach (var item in db.gois)
                                    {
                                        if (!dsGoi.Contains(item))
                                        {
                                            dsGoi.Add(item);
                                        }
                                    }
                                    foreach (var item in dsGoi)
                                    {
                                        <div class="col-md-12 col-lg-12 col-12 mb-5 mb-lg-0">
                                            <a href="@Url.Content("/Goi/chiTietGoi/"+item.magoi)" class="text-black">
                                                <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
                                                    <div class="icon text-center"><i class="fas fa-gem text-danger"></i></div>
                                                    <h4 class="title">@item.tengoi</h4>
                                                    <p class="description"><strong>Giá:</strong>: @String.Format("{0:n0}", item.gia)&nbsp; <strong>VNĐ</strong></p>
                                                </div>
                                            </a>
                                        </div>
                                        <div>&nbsp;</div>
                                    }

                                }
                                

                            </div>
                        </section>

                    </div>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Chi tiết gói/ thanh toán Section -->

QLSachOnline/QLSachOnline/Views/Goi/formSuaGoi.cshtml
@model QLSachOnline.Models.goi

@{
    ViewBag.Title = "Sửa gói";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="col-md-10 col-10">
    <h2>Sửa gói Premium</h2>
    @using (Html.BeginForm("suaGoi", "Goi", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.magoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.magoi, new { htmlAttributes = new { @class = "form-control",@readonly="readonly" } })
                    @Html.ValidationMessageFor(model => model.magoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tengoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tengoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tengoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.motagoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.motagoi, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.motagoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.thoihan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.thoihan, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                    @Html.ValidationMessageFor(model => model.thoihan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                    @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

QLSachOnline/QLSachOnline/Views/Goi/formThemGoi.cshtml
@model QLSachOnline.Models.goi

@{
    ViewBag.Title = "Thêm gói";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="col-md-10 col-10">
    <h2>Thêm gói Premium</h2>
    @using (Html.BeginForm("themGoi","Goi",FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.magoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.magoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.magoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tengoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tengoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tengoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.motagoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.motagoi, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.motagoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.thoihan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.thoihan, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                    @Html.ValidationMessageFor(model => model.thoihan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                    @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

QLSachOnline/QLSachOnline/Views/Goi/formXoaGoi.cshtml
@model QLSachOnline.Models.goi

@{
    ViewBag.Title = "Xóa gói";
    Layout = "~/Views/_Layout/_LayoutAdmin.cshtml";
}

<div class="col-md-10 col-10">
    <h2>Xóa gói <strong>Premium</strong> @Model.tengoi</h2>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.magoi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.magoi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tengoi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tengoi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.motagoi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.motagoi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.thoihan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.thoihan)
            </dd>

        </dl>
        @if (ViewBag.flagCheck != null)
        {
            using (Html.BeginForm("xoaGoi", "Goi", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(Model => Model.magoi)
                <div class="alert alert-danger">Bạn có chắc là muốn <strong>xóa</strong> đi gói Premium này ?</div>
                <div class="form-actions no-color">
                    <input type="submit" value="Xóa" class="btn btn-primary" />
                </div>
            }
            }
            else
            {
                <div class="alert alert-danger"><strong>Không thể xóa !</strong> Bạn không thể xóa gói này !</div>
            }
    </div>
</div>